###
GET http://localhost:5500/api/autor

###

POST http://localhost:5100/api/autor
Content-Type: application/json

{
    "name": "Pedro"
}

###

POST http://localhost:5500/api/autor
Content-Type: application/json

{
    "name": "Pedro",
    "libros": ["123", "", "345"],
    "premios": ["Premio Newbury"]
}

###

GET http://localhost:5500/api/autor/61de1ecbc18e88e93f6b0e32

###

GET http://localhost:5500/api/autor/detalles/61de1ecbc18e88e93f6b0e32

###

POST http://localhost:5500/api/autor/gana/61de1c1bdab07a5a6a3920cb/100

