###

POST http://localhost:5100/api/usuario
Content-Type: application/json

{
   "usuario": "mrmiyagui",
   "nombres": "Mister",
   "apellidos": "Miyagui",
   "correo": "mrm@gmail.com",
   "password": "12345678",
   "confirmPassword": "12345678"

}

###

POST http://localhost:5100/api/usuario/login
Content-Type: application/json

{
   "correo": "pedro@gmail.com",
   "password": "12345678"
}

###

GET http://localhost:5100/api/usuario